# Generated by Django 5.2.7 on 2025-12-01 06:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTokenModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('key', models.TextField(unique=True)),
                ('last_symbols', models.CharField(max_length=4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'service_token',
            },
        ),
        migrations.CreateModel(
            name='ServiceTokenPermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='disable')),
                ('tts', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='disable')),
                ('stt', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='disable')),
                ('history', models.CharField(choices=[('read', 'read'), ('write', 'write'), ('all', 'all'), ('disable', 'disable')], default='disable')),
                ('monitoring', models.CharField(choices=[('read', 'read'), ('write', 'write'), ('all', 'all'), ('disable', 'disable')], default='disable')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'service_token_permission',
            },
        ),
    ]
