# Generated by Django 5.2.7 on 2025-11-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetokenmodel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicetokenmodel',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicetokenmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ServiceTokenPermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tts', models.BooleanField(default=False)),
                ('stt', models.BooleanField(default=False)),
                ('llm', models.BooleanField(default=False)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token permission',
                'verbose_name_plural': 'Token permissions',
                'db_table': 'service_token_permission',
            },
        ),
        migrations.CreateModel(
            name='ServiceTokenStatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tts', models.PositiveBigIntegerField(default=0)),
                ('stt', models.PositiveBigIntegerField(default=0)),
                ('llm', models.PositiveBigIntegerField(default=0)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token stats',
                'verbose_name_plural': 'Token stats',
                'db_table': 'service_token_stats',
            },
        ),
    ]
