# Generated by Django 5.2.7 on 2025-11-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicellmsessionmodel',
            name='token',
        ),
        migrations.RemoveField(
            model_name='servicesttmodel',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='servicesttmodel',
            name='token',
        ),
        migrations.RemoveField(
            model_name='servicettsmodel',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='servicettsmodel',
            name='token',
        ),
        migrations.DeleteModel(
            name='ServiceLLMMessageModel',
        ),
        migrations.DeleteModel(
            name='ServiceLLMSessionModel',
        ),
        migrations.DeleteModel(
            name='ServiceSTTModel',
        ),
        migrations.DeleteModel(
            name='ServiceTTSModel',
        ),
    ]
