# Generated by Django 5.2.7 on 2025-11-26 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_servicellmsessionmodel_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetokenmodel',
            name='last_used_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
