# Generated by Django 5.2.7 on 2025-11-18 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicetokenmodel_is_blocked_servicetokenmodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTokenUsageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tts', models.PositiveBigIntegerField(default=0)),
                ('stt', models.PositiveBigIntegerField(default=0)),
                ('llm', models.PositiveBigIntegerField(default=0)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token usage',
                'verbose_name_plural': 'Token usages',
                'db_table': 'service_token_usage',
            },
        ),
        migrations.DeleteModel(
            name='ServiceTokenStatsModel',
        ),
    ]
