# Generated by Django 5.2.7 on 2025-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_servicetokenmodel_last_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetokenpermissionmodel',
            name='history',
            field=models.CharField(choices=[('read', 'read'), ('write', 'write'), ('disable', 'disable')], default='disable'),
        ),
        migrations.AddField(
            model_name='servicetokenpermissionmodel',
            name='monitoring',
            field=models.CharField(choices=[('read', 'read'), ('write', 'write'), ('disable', 'disable')], default='disable'),
        ),
        migrations.AlterField(
            model_name='servicetokenpermissionmodel',
            name='llm',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='disable'),
        ),
        migrations.AlterField(
            model_name='servicetokenpermissionmodel',
            name='stt',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='disable'),
        ),
        migrations.AlterField(
            model_name='servicetokenpermissionmodel',
            name='tts',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='disable'),
        ),
    ]
