# Generated by Django 5.2.7 on 2025-11-18 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicetokenusagemodel_delete_servicetokenstatsmodel'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetokenpermissionmodel',
            options={'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.CreateModel(
            name='ServiceLLMSessionModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('context', models.PositiveIntegerField(default=0)),
                ('context_expense', models.PositiveIntegerField(default=0)),
                ('is_streaming', models.BooleanField(default=False)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'service_llm_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLLMMessageModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=20)),
                ('content', models.TextField(default='')),
                ('mdl', models.CharField(max_length=50)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='service.servicellmsessionmodel')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'service_llm_message',
            },
        ),
        migrations.CreateModel(
            name='ServiceSTTModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(blank=True, null=True)),
                ('mdl', models.CharField(max_length=50)),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_stt', to='shared.audiomodel')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stt', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'STT',
                'verbose_name_plural': 'STT',
                'db_table': 'service_stt_data',
            },
        ),
        migrations.CreateModel(
            name='ServiceTTSModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField()),
                ('emotion', models.CharField(max_length=50)),
                ('mdl', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tts', to='shared.audiomodel')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tts', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'TTS',
                'verbose_name_plural': 'TTS',
                'db_table': 'service_tts_data',
            },
        ),
        migrations.DeleteModel(
            name='ServiceTokenUsageModel',
        ),
    ]
