# Generated by Django 5.2.7 on 2025-11-18 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_servicetokenpermissionmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicellmsessionmodel',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='service.servicetokenmodel'),
            preserve_default=False,
        ),
    ]
