# Generated by Django 5.2.7 on 2025-11-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_servicetokenpermissionmodel_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetokenpermissionmodel',
            name='history',
            field=models.CharField(choices=[('read', 'read'), ('write', 'write'), ('all', 'all'), ('disable', 'disable')], default='disable'),
        ),
        migrations.AlterField(
            model_name='servicetokenpermissionmodel',
            name='monitoring',
            field=models.CharField(choices=[('read', 'read'), ('write', 'write'), ('all', 'all'), ('disable', 'disable')], default='disable'),
        ),
    ]
