# Generated by Django 5.2.7 on 2025-11-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_servicellmsessionmodel_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicellmsessionmodel',
            name='is_streaming',
        ),
        migrations.RemoveField(
            model_name='servicellmsessionmodel',
            name='title',
        ),
    ]
