# Generated by Django 5.2.7 on 2026-01-15 12:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='STTModelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('cash', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'db_table': 'stt_model',
            },
        ),
        migrations.CreateModel(
            name='TokenSTTModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(blank=True, null=True)),
                ('mdl', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.audiomodel')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token list',
                'verbose_name_plural': 'Token list',
                'db_table': 'token_stt',
            },
        ),
        migrations.CreateModel(
            name='UserSTTModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(blank=True, null=True)),
                ('mdl', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.audiomodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User list',
                'verbose_name_plural': 'User list',
                'db_table': 'user_stt',
            },
        ),
    ]
