# Generated by Django 5.2.7 on 2025-10-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sttmodelmodel',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
    ]
