# Generated by Django 5.2.7 on 2025-11-25 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_servicellmsessionmodel_token_and_more'),
        ('shared', '0001_initial'),
        ('stt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STTModel',
            new_name='UserSTTModel',
        ),
        migrations.AlterModelOptions(
            name='usersttmodel',
            options={'verbose_name': 'User list', 'verbose_name_plural': 'User list'},
        ),
        migrations.AlterModelTable(
            name='usersttmodel',
            table='user_stt',
        ),
        migrations.CreateModel(
            name='TokenSTTModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(blank=True, null=True)),
                ('mdl', models.CharField(max_length=50)),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.audiomodel')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token list',
                'verbose_name_plural': 'Token list',
                'db_table': 'token_stt',
            },
        ),
    ]
