# Generated by Django 5.2.7 on 2025-11-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0003_alter_tokensttmodel_token_alter_usersttmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensttmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersttmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
