# Generated by Django 5.2.7 on 2025-11-20 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLLMErrorLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_log', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Service llm',
                'verbose_name_plural': 'Service llm',
                'db_table': 'service_llm_log',
            },
        ),
        migrations.CreateModel(
            name='ServiceSTTErrorLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.audiomodel')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stt_log', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Service stt',
                'verbose_name_plural': 'Service stt',
                'db_table': 'service_stt_log',
            },
        ),
        migrations.CreateModel(
            name='ServiceTTSErrorLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('text', models.TextField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_log', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Service tts',
                'verbose_name_plural': 'Service tts',
                'db_table': 'service_tts_log',
            },
        ),
        migrations.CreateModel(
            name='UserLLMErrorLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User llm',
                'verbose_name_plural': 'User llm',
                'db_table': 'user_llm_log',
            },
        ),
        migrations.CreateModel(
            name='UserSTTErrorLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.audiomodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stt_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User stt',
                'verbose_name_plural': 'User stt',
                'db_table': 'user_stt_log',
            },
        ),
        migrations.CreateModel(
            name='UserTTSErrorLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('text', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User tts',
                'verbose_name_plural': 'User tts',
                'db_table': 'user_tts_log',
            },
        ),
    ]
