# Generated by Django 5.2.7 on 2025-11-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicellmerrorlogmodel',
            options={'verbose_name': 'Service llm', 'verbose_name_plural': 'Service llm'},
        ),
        migrations.AlterModelOptions(
            name='servicestterrorlogmodel',
            options={'verbose_name': 'Service stt', 'verbose_name_plural': 'Service stt'},
        ),
        migrations.AlterModelOptions(
            name='servicettserrorlogmodel',
            options={'verbose_name': 'Service tts', 'verbose_name_plural': 'Service tts'},
        ),
        migrations.AlterModelOptions(
            name='userllmerrorlogmodel',
            options={'verbose_name': 'User llm', 'verbose_name_plural': 'User llm'},
        ),
        migrations.AlterModelOptions(
            name='userstterrorlogmodel',
            options={'verbose_name': 'User stt', 'verbose_name_plural': 'User stt'},
        ),
        migrations.AlterModelOptions(
            name='userttserrorlogmodel',
            options={'verbose_name': 'User tts', 'verbose_name_plural': 'User tts'},
        ),
        migrations.RenameField(
            model_name='servicellmerrorlogmodel',
            old_name='service',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='servicestterrorlogmodel',
            old_name='service',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='servicettserrorlogmodel',
            old_name='service',
            new_name='token',
        ),
    ]
