# Generated by Django 5.2.7 on 2025-11-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
        ('service', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicestterrorlogmodel',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='servicestterrorlogmodel',
            name='token',
        ),
        migrations.RemoveField(
            model_name='servicettserrorlogmodel',
            name='token',
        ),
        migrations.CreateModel(
            name='TokenLLMErrorLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_log', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token llm',
                'verbose_name_plural': 'Token llm',
                'db_table': 'token_llm_log',
            },
        ),
        migrations.CreateModel(
            name='TokenSTTErrorLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.audiomodel')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stt_log', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token stt',
                'verbose_name_plural': 'Token stt',
                'db_table': 'token_stt_log',
            },
        ),
        migrations.CreateModel(
            name='TokenTTSErrorLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('text', models.TextField(blank=True, null=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_log', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token tts',
                'verbose_name_plural': 'Token tts',
                'db_table': 'token_tts_log',
            },
        ),
        migrations.DeleteModel(
            name='ServiceLLMErrorLogModel',
        ),
        migrations.DeleteModel(
            name='ServiceSTTErrorLogModel',
        ),
        migrations.DeleteModel(
            name='ServiceTTSErrorLogModel',
        ),
    ]
