# Generated by Django 5.2.7 on 2026-01-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingerrorlogmodel',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_log', to='billing.billingmodel'),
        ),
    ]
