# Generated by Django 5.2.7 on 2025-11-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_remove_servicestterrorlogmodel_audio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenllmerrorlogmodel',
            old_name='key',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='tokenstterrorlogmodel',
            old_name='key',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='tokenttserrorlogmodel',
            old_name='key',
            new_name='token',
        ),
    ]
