# Generated by Django 5.2.7 on 2026-01-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_billingerrorlogmodel_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingerrorlogmodel',
            name='billing',
        ),
        migrations.AddField(
            model_name='billingerrorlogmodel',
            name='invoice',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
