# Generated by Django 5.2.7 on 2026-01-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_remove_billingerrorlogmodel_billing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingerrorlogmodel',
            name='invoice',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
