# Generated by Django 5.2.7 on 2026-01-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_billingerrorlogmodel_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingerrorlogmodel',
            name='invoice',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
