# Generated by Django 5.2.7 on 2026-01-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_alter_billingerrorlogmodel_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingerrorlogmodel',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
