# Generated by Django 5.2.7 on 2025-11-17 06:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLLMRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM rate',
                'verbose_name_plural': 'LLM rates',
                'db_table': 'plan_llm_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanLLMCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('llm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='plan.planllmratemodel')),
            ],
            options={
                'verbose_name': 'LLM credit rate',
                'verbose_name_plural': 'LLM credit rates',
                'db_table': 'plan_llm_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('llm_session', models.PositiveIntegerField(default=0)),
                ('llm_context', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
                'db_table': 'plan',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PlanAnnualModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annual', to='plan.planmodel')),
            ],
            options={
                'verbose_name': 'Annual fund',
                'verbose_name_plural': 'Annual funds',
                'db_table': 'plan_annual',
            },
        ),
        migrations.CreateModel(
            name='PlanMonthlyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monthly', to='plan.planmodel')),
            ],
            options={
                'verbose_name': 'Monthly fund',
                'verbose_name_plural': 'Monthly funds',
                'db_table': 'plan_monthly',
            },
        ),
        migrations.CreateModel(
            name='PlanRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='plan.planmodel')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
                'db_table': 'plan_rate',
            },
        ),
        migrations.AddField(
            model_name='planllmratemodel',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm', to='plan.planratemodel'),
        ),
        migrations.CreateModel(
            name='PlanSTTRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stt', to='plan.planratemodel')),
            ],
            options={
                'verbose_name': 'STT rate',
                'verbose_name_plural': 'STT rates',
                'db_table': 'plan_stt_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanSTTCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('stt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='plan.plansttratemodel')),
            ],
            options={
                'verbose_name': 'STT credit rate',
                'verbose_name_plural': 'STT credit rates',
                'db_table': 'plan_stt_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanTTSRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts', to='plan.planratemodel')),
            ],
            options={
                'verbose_name': 'TTS rate',
                'verbose_name_plural': 'TTS rates',
                'db_table': 'plan_tts_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanTTSCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('tts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='plan.planttsratemodel')),
            ],
            options={
                'verbose_name': 'TTS credit rate',
                'verbose_name_plural': 'TTS credit rates',
                'db_table': 'plan_tts_credit_rate',
            },
        ),
    ]
