# Generated by Django 5.2.7 on 2025-10-15 12:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_sessions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'plan_chat_rate',
            },
        ),
        migrations.CreateModel(
            name='ChatCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.PositiveBigIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='plan.chatratemodel')),
            ],
            options={
                'db_table': 'plan_chat_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='ChatSessionRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.PositiveBigIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='plan.chatratemodel')),
            ],
            options={
                'db_table': 'plan_chat_session_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plans',
                'verbose_name_plural': 'Plans',
                'db_table': 'plan',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PlanAnnualModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annual', to='plan.planmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanMonthlyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monthly', to='plan.planmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='plan.planmodel')),
            ],
            options={
                'db_table': 'plan_rate',
            },
        ),
        migrations.AddField(
            model_name='chatratemodel',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='plan.planratemodel'),
        ),
        migrations.CreateModel(
            name='STTRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stt', to='plan.planratemodel')),
            ],
            options={
                'db_table': 'plan_stt_rate',
            },
        ),
        migrations.CreateModel(
            name='STTCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.PositiveBigIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('stt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='plan.sttratemodel')),
            ],
            options={
                'db_table': 'plan_stt_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='TTSRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts', to='plan.planratemodel')),
            ],
            options={
                'db_table': 'plan_tts_rate',
            },
        ),
        migrations.CreateModel(
            name='TTSCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.PositiveBigIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('tts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='plan.ttsratemodel')),
            ],
            options={
                'db_table': 'plan_tts_credit_rate',
            },
        ),
    ]
