# Generated by Django 5.2.7 on 2025-10-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatcreditratemodel',
            options={'verbose_name': 'Chat credit rate', 'verbose_name_plural': 'Chat credit rates'},
        ),
        migrations.AlterModelOptions(
            name='chatratemodel',
            options={'verbose_name': 'Chat rate', 'verbose_name_plural': 'Chat rates'},
        ),
        migrations.AlterModelOptions(
            name='chatsessionratemodel',
            options={'verbose_name': 'Chat session rate', 'verbose_name_plural': 'Chat session rates'},
        ),
        migrations.AlterModelOptions(
            name='planannualmodel',
            options={'verbose_name': 'Annual cost', 'verbose_name_plural': 'Annual cost'},
        ),
        migrations.AlterModelOptions(
            name='planmodel',
            options={'ordering': ['pk'], 'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
        migrations.AlterModelOptions(
            name='planmonthlymodel',
            options={'verbose_name': 'Monthly cost', 'verbose_name_plural': 'Monthly cost'},
        ),
        migrations.AlterModelOptions(
            name='planratemodel',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
        migrations.AlterModelOptions(
            name='sttcreditratemodel',
            options={'verbose_name': 'STT credit rate', 'verbose_name_plural': 'STT credit rates'},
        ),
        migrations.AlterModelOptions(
            name='sttratemodel',
            options={'verbose_name': 'STT rate', 'verbose_name_plural': 'STT rates'},
        ),
        migrations.AlterModelOptions(
            name='ttscreditratemodel',
            options={'verbose_name': 'TTS credit rate', 'verbose_name_plural': 'TTS credit rates'},
        ),
        migrations.AlterModelOptions(
            name='ttsratemodel',
            options={'verbose_name': 'TTS rate', 'verbose_name_plural': 'TTS rates'},
        ),
        migrations.AlterModelTable(
            name='planannualmodel',
            table='plan_annual',
        ),
        migrations.AlterModelTable(
            name='planmonthlymodel',
            table='plan_monthly',
        ),
    ]
