# Generated by Django 5.2.7 on 2025-10-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_chatcreditratemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planannualmodel',
            options={'verbose_name': 'Annual fund', 'verbose_name_plural': 'Annual funds'},
        ),
        migrations.AlterModelOptions(
            name='planmonthlymodel',
            options={'verbose_name': 'Monthly fund', 'verbose_name_plural': 'Monthly funds'},
        ),
        migrations.RemoveField(
            model_name='chatcreditratemodel',
            name='reset',
        ),
        migrations.RemoveField(
            model_name='chatcreditratemodel',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='sttcreditratemodel',
            name='reset',
        ),
        migrations.RemoveField(
            model_name='sttcreditratemodel',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='ttscreditratemodel',
            name='reset',
        ),
        migrations.RemoveField(
            model_name='ttscreditratemodel',
            name='usage',
        ),
    ]
