# Generated by Django 5.2.7 on 2025-10-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_planannualmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsessionratemodel',
            name='usage',
        ),
    ]
