# Generated by Django 5.2.7 on 2025-10-16 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_remove_chatsessionratemodel_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsessionratemodel',
            name='limit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
