# Generated by Django 5.2.7 on 2025-10-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_alter_chatsessionratemodel_limit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatCreditRateModel',
            new_name='PlanChatCreditRateModel',
        ),
        migrations.RenameModel(
            old_name='ChatRateModel',
            new_name='PlanChatRateModel',
        ),
        migrations.RenameModel(
            old_name='ChatSessionRateModel',
            new_name='PlanChatSessionRateModel',
        ),
        migrations.RenameModel(
            old_name='STTCreditRateModel',
            new_name='PlanSTTCreditRateModel',
        ),
        migrations.RenameModel(
            old_name='STTRateModel',
            new_name='PlanSTTRateModel',
        ),
        migrations.RenameModel(
            old_name='TTSCreditRateModel',
            new_name='PlanTTSCreditRateModel',
        ),
        migrations.RenameModel(
            old_name='TTSRateModel',
            new_name='PlanTTSRateModel',
        ),
    ]
