# Generated by Django 5.2.7 on 2025-10-17 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_rename_chatcreditratemodel_planchatcreditratemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planchatcreditratemodel',
            name='limit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plansttcreditratemodel',
            name='limit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='planttscreditratemodel',
            name='limit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
