# Generated by Django 5.2.7 on 2025-10-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_alter_planchatcreditratemodel_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planchatratemodel',
            name='max_contexts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
