# Generated by Django 5.2.7 on 2025-10-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_planchatratemodel_max_contexts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planchatratemodel',
            name='max_contexts',
        ),
        migrations.RemoveField(
            model_name='planchatratemodel',
            name='max_sessions',
        ),
        migrations.AddField(
            model_name='planmodel',
            name='chat_context',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='chat_session',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
