# Generated by Django 5.2.7 on 2025-11-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_remove_planchatratemodel_max_contexts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanChatSessionRateModel',
        ),
    ]
