# Generated by Django 5.2.7 on 2025-10-15 12:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_sessions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sub_chat_rate',
            },
        ),
        migrations.CreateModel(
            name='STTRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sub_stt_rate',
            },
        ),
        migrations.CreateModel(
            name='ChatCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.PositiveBigIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='subscription.chatratemodel')),
            ],
            options={
                'db_table': 'sub_chat_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='ChatSessionRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.PositiveBigIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='subscription.chatratemodel')),
            ],
            options={
                'db_table': 'sub_chat_session_rate',
            },
        ),
        migrations.CreateModel(
            name='STTCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.PositiveBigIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('stt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='subscription.sttratemodel')),
            ],
            options={
                'db_table': 'sub_stt_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('expense', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('auto_renew', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('canceled', 'canceled')], default='active')),
                ('period', models.CharField(choices=[('monthly', 'monthly'), ('annual', 'annual')], default='monthly')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'sub',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='subscription.subscriptionmodel')),
            ],
            options={
                'db_table': 'sub_rate',
            },
        ),
        migrations.AddField(
            model_name='sttratemodel',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stt', to='subscription.subscriptionratemodel'),
        ),
        migrations.AddField(
            model_name='chatratemodel',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='subscription.subscriptionratemodel'),
        ),
        migrations.CreateModel(
            name='TTSRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts', to='subscription.subscriptionratemodel')),
            ],
            options={
                'db_table': 'sub_tts_rate',
            },
        ),
        migrations.CreateModel(
            name='TTSCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.PositiveBigIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('tts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='subscription.ttsratemodel')),
            ],
            options={
                'db_table': 'sub_tts_credit_rate',
            },
        ),
    ]
