# Generated by Django 5.2.7 on 2025-11-17 06:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLLMRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM rate',
                'verbose_name_plural': 'LLM rates',
                'db_table': 'sub_llm_rate',
            },
        ),
        migrations.CreateModel(
            name='SubRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
                'db_table': 'sub_rate',
            },
        ),
        migrations.CreateModel(
            name='SubLLMCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('llm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='subscription.subllmratemodel')),
            ],
            options={
                'verbose_name': 'LLM credit rate',
                'verbose_name_plural': 'LLM credit rates',
                'db_table': 'sub_llm_credit_rate',
            },
        ),
        migrations.AddField(
            model_name='subllmratemodel',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm', to='subscription.subratemodel'),
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_expense', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('llm_session', models.PositiveIntegerField(default=0)),
                ('llm_context', models.PositiveIntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('canceled', 'canceled')], default='active')),
                ('period', models.CharField(choices=[('monthly', 'monthly'), ('annual', 'annual')], default='monthly')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
                'db_table': 'sub',
            },
        ),
        migrations.AddField(
            model_name='subratemodel',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='subscription.subscriptionmodel'),
        ),
        migrations.CreateModel(
            name='SubSTTRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stt', to='subscription.subratemodel')),
            ],
            options={
                'verbose_name': 'STT rate',
                'verbose_name_plural': 'STT rates',
                'db_table': 'sub_stt_rate',
            },
        ),
        migrations.CreateModel(
            name='SubSTTCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('stt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='subscription.substtratemodel')),
            ],
            options={
                'verbose_name': 'Stt credit rate',
                'verbose_name_plural': 'STT credit rates',
                'db_table': 'sub_stt_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='SubTTSRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts', to='subscription.subratemodel')),
            ],
            options={
                'verbose_name': 'TTS rate',
                'verbose_name_plural': 'TTS rates',
                'db_table': 'sub_tts_rate',
            },
        ),
        migrations.CreateModel(
            name='SubTTSCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('tts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='subscription.subttsratemodel')),
            ],
            options={
                'verbose_name': 'TTS credit rate',
                'verbose_name_plural': 'TTS credit rates',
                'db_table': 'sub_tts_credit_rate',
            },
        ),
    ]
