# Generated by Django 5.2.7 on 2025-11-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='llm_session_expense',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
