# Generated by Django 5.2.7 on 2025-10-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_chatsessionratemodel_limit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatCreditRateModel',
            new_name='SubChatCreditRateModel',
        ),
        migrations.RenameModel(
            old_name='ChatRateModel',
            new_name='SubChatRateModel',
        ),
        migrations.RenameModel(
            old_name='ChatSessionRateModel',
            new_name='SubChatSessionRateModel',
        ),
        migrations.RenameModel(
            old_name='SubscriptionRateModel',
            new_name='SubRateModel',
        ),
        migrations.RenameModel(
            old_name='STTCreditRateModel',
            new_name='SubSTTCreditRateModel',
        ),
        migrations.RenameModel(
            old_name='STTRateModel',
            new_name='SubSTTRateModel',
        ),
        migrations.RenameModel(
            old_name='TTSCreditRateModel',
            new_name='SubTTSCreditRateModel',
        ),
        migrations.RenameModel(
            old_name='TTSRateModel',
            new_name='SubTTSRateModel',
        ),
    ]
