# Generated by Django 5.2.7 on 2025-10-17 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_rename_chatcreditratemodel_subchatcreditratemodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subchatcreditratemodel',
            options={'verbose_name': 'Chat credit rate', 'verbose_name_plural': 'Chat credit rates'},
        ),
        migrations.AlterModelOptions(
            name='subchatratemodel',
            options={'verbose_name': 'Chat rate', 'verbose_name_plural': 'Chat rates'},
        ),
        migrations.AlterModelOptions(
            name='subchatsessionratemodel',
            options={'verbose_name': 'Chat session rate', 'verbose_name_plural': 'Chat session rates'},
        ),
        migrations.AlterModelOptions(
            name='subratemodel',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionmodel',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
        migrations.AlterModelOptions(
            name='substtcreditratemodel',
            options={'verbose_name': 'Stt credit rate', 'verbose_name_plural': 'STT credit rates'},
        ),
        migrations.AlterModelOptions(
            name='substtratemodel',
            options={'verbose_name': 'STT rate', 'verbose_name_plural': 'STT rates'},
        ),
        migrations.AlterModelOptions(
            name='subttscreditratemodel',
            options={'verbose_name': 'TTS credit rate', 'verbose_name_plural': 'TTS credit rates'},
        ),
        migrations.AlterModelOptions(
            name='subttsratemodel',
            options={'verbose_name': 'TTS rate', 'verbose_name_plural': 'TTS rates'},
        ),
        migrations.AlterField(
            model_name='subchatcreditratemodel',
            name='limit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='substtcreditratemodel',
            name='limit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subttscreditratemodel',
            name='limit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
