# Generated by Django 5.2.7 on 2025-10-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subchatcreditratemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subchatratemodel',
            name='max_contexts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
