# Generated by Django 5.2.7 on 2025-10-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subchatratemodel_max_contexts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionmodel',
            old_name='expense',
            new_name='credit_expense',
        ),
        migrations.RemoveField(
            model_name='subchatratemodel',
            name='max_contexts',
        ),
        migrations.RemoveField(
            model_name='subchatratemodel',
            name='max_sessions',
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='chat_context',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='chat_context_expense',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='chat_session',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='chat_session_expense',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='session',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='session_expense',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
