# Generated by Django 5.2.7 on 2025-11-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_rename_expense_subscriptionmodel_credit_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='chat_context_expense',
        ),
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='session',
        ),
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='session_expense',
        ),
        migrations.DeleteModel(
            name='SubChatSessionRateModel',
        ),
    ]
