# Generated by Django 5.2.7 on 2025-11-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userttserrorlogmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ServiceTTSErrorLogModel',
        ),
        migrations.DeleteModel(
            name='UserTTSErrorLogModel',
        ),
    ]
