# Generated by Django 5.2.7 on 2025-11-25 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_servicellmsessionmodel_token_and_more'),
        ('shared', '0002_alter_audiomodel_user'),
        ('tts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTTSModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField()),
                ('emotion', models.CharField(max_length=50)),
                ('mdl', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.audiomodel')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'List',
                'db_table': 'token_tts',
            },
        ),
        migrations.CreateModel(
            name='UserTTSModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField()),
                ('emotion', models.CharField(max_length=50)),
                ('mdl', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.audiomodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'List',
                'db_table': 'user_tts',
            },
        ),
        migrations.DeleteModel(
            name='TTSModel',
        ),
    ]
