# Generated by Django 5.2.7 on 2025-11-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0002_tokenttsmodel_userttsmodel_delete_ttsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenttsmodel',
            options={'verbose_name': 'Token list', 'verbose_name_plural': 'Token list'},
        ),
        migrations.AlterModelOptions(
            name='userttsmodel',
            options={'verbose_name': 'User list', 'verbose_name_plural': 'User list'},
        ),
        migrations.AddField(
            model_name='tokenttsmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userttsmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
