# Generated by Django 5.2.7 on 2026-01-23 14:18

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user')),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('regular_auth', models.BooleanField(default=False)),
                ('google_auth', models.BooleanField(default=False)),
                ('facebook_auth', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_password_update', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmOtpModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_attempts', models.SmallIntegerField(default=3)),
                ('remaining_resends', models.SmallIntegerField(default=5)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_attempt', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_resend', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('sent', 'Sent')], default='processing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email confirmation otp',
                'verbose_name_plural': 'Email confirmation otps',
                'db_table': 'email_otp',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, max_length=250, null=True, unique=True)),
                ('token', models.CharField(unique=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('sent', 'Sent')], default='processing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password reset token',
                'verbose_name_plural': 'Password reset tokens',
                'db_table': 'password_reset_token',
            },
        ),
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to=accounts.models.generate_picture_name)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'db_table': 'picture',
            },
        ),
        migrations.CreateModel(
            name='SocialAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], max_length=20, verbose_name='provider')),
                ('provider_user_id', models.CharField(db_index=True, max_length=255, verbose_name='provider user ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social account',
                'verbose_name_plural': 'Social accounts',
                'db_table': 'social_accounts',
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
