# Generated by Django 5.2.7 on 2025-11-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusermodel_last_logged_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='last_logged_at',
            new_name='last_used_at',
        ),
    ]
