# Generated by Django 5.2.7 on 2026-01-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billingmodel_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='invoice',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
