# Generated by Django 5.2.7 on 2026-01-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_billingmodel_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='invoice',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
