# Generated by Django 5.2.7 on 2026-01-16 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_billingmodel_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
