# Generated by Django 5.2.7 on 2026-01-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_billingmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='transaction_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
