# Generated by Django 5.2.7 on 2025-11-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenllmmessagemodel',
            options={'verbose_name': 'Token message', 'verbose_name_plural': 'Token messages'},
        ),
        migrations.AlterModelOptions(
            name='tokenllmsessionmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Token session', 'verbose_name_plural': 'Token sessions'},
        ),
        migrations.AlterModelOptions(
            name='userllmmessagemodel',
            options={'verbose_name': 'User message', 'verbose_name_plural': 'User messages'},
        ),
        migrations.AlterModelOptions(
            name='userllmsessionmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'User session', 'verbose_name_plural': 'User sessions'},
        ),
    ]
