# Generated by Django 5.2.7 on 2025-11-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userllmerrorlogmodel',
            old_name='text',
            new_name='content',
        ),
    ]
