# Generated by Django 5.2.7 on 2025-11-25 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_alter_tokenllmmessagemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenllmmessagemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='llm.tokenllmsessionmodel'),
        ),
        migrations.AlterField(
            model_name='userllmmessagemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='llm.userllmsessionmodel'),
        ),
    ]
