# Generated by Django 5.2.7 on 2025-11-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_rename_text_userllmerrorlogmodel_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userllmerrorlogmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ServiceLLMErrorLogModel',
        ),
        migrations.DeleteModel(
            name='UserLLMErrorLogModel',
        ),
    ]
