# Generated by Django 5.2.7 on 2025-11-20 10:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLLMRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan LLM',
                'verbose_name_plural': 'Plan LLM',
                'db_table': 'plan_llm_rate',
            },
        ),
        migrations.CreateModel(
            name='TokenLLMRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token LLM',
                'verbose_name_plural': 'Token LLM',
                'db_table': 'token_llm_rate',
            },
        ),
        migrations.CreateModel(
            name='UserLLMRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User LLM',
                'verbose_name_plural': 'User LLM',
                'db_table': 'user_llm_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanLLMCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('llm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='rate.planllmratemodel')),
            ],
            options={
                'verbose_name': 'Plan LLM credit',
                'verbose_name_plural': 'Plan LLM credits',
                'db_table': 'plan_llm_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='plan.planmodel')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plan',
                'db_table': 'plan_rate',
            },
        ),
        migrations.AddField(
            model_name='planllmratemodel',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm', to='rate.planratemodel'),
        ),
        migrations.CreateModel(
            name='PlanSTTRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stt', to='rate.planratemodel')),
            ],
            options={
                'verbose_name': 'Plan STT',
                'verbose_name_plural': 'Plan STT',
                'db_table': 'plan_stt_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanSTTCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('stt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='rate.plansttratemodel')),
            ],
            options={
                'verbose_name': 'Plan STT credit',
                'verbose_name_plural': 'Plan STT credits',
                'db_table': 'plan_stt_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanTTSRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts', to='rate.planratemodel')),
            ],
            options={
                'verbose_name': 'Plan TTS',
                'verbose_name_plural': 'Plan TTS',
                'db_table': 'plan_tts_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanTTSCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('tts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='rate.planttsratemodel')),
            ],
            options={
                'verbose_name': 'Plan TTS credit',
                'verbose_name_plural': 'Plan TTS credits',
                'db_table': 'plan_tts_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='TokenLLMCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('llm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='rate.tokenllmratemodel')),
            ],
            options={
                'verbose_name': 'Token LLM credits',
                'verbose_name_plural': 'Token LLM credits',
                'db_table': 'token_llm_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='TokenRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Token',
                'db_table': 'token_rate',
            },
        ),
        migrations.AddField(
            model_name='tokenllmratemodel',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm', to='rate.tokenratemodel'),
        ),
        migrations.CreateModel(
            name='TokenSTTRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stt', to='rate.tokenratemodel')),
            ],
            options={
                'verbose_name': 'Token STT',
                'verbose_name_plural': 'Token STT',
                'db_table': 'token_stt_rate',
            },
        ),
        migrations.CreateModel(
            name='TokenSTTCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('stt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='rate.tokensttratemodel')),
            ],
            options={
                'verbose_name': 'Token Stt credit',
                'verbose_name_plural': 'Token STT credits',
                'db_table': 'token_stt_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='TokenTTSRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts', to='rate.tokenratemodel')),
            ],
            options={
                'verbose_name': 'Token TTS',
                'verbose_name_plural': 'Token TTS',
                'db_table': 'token_tts_rate',
            },
        ),
        migrations.CreateModel(
            name='TokenTTSCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('tts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='rate.tokenttsratemodel')),
            ],
            options={
                'verbose_name': 'Token TTS credit',
                'verbose_name_plural': 'Token TTS credits',
                'db_table': 'token_tts_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='UserLLMCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('llm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='rate.userllmratemodel')),
            ],
            options={
                'verbose_name': 'User LLM credit',
                'verbose_name_plural': 'User LLM credits',
                'db_table': 'user_llm_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='UserRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
                'db_table': 'user_rate',
            },
        ),
        migrations.AddField(
            model_name='userllmratemodel',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm', to='rate.userratemodel'),
        ),
        migrations.CreateModel(
            name='UserSTTRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stt', to='rate.userratemodel')),
            ],
            options={
                'verbose_name': 'User STT',
                'verbose_name_plural': 'User STT',
                'db_table': 'user_stt_rate',
            },
        ),
        migrations.CreateModel(
            name='UserSTTCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('stt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='rate.usersttratemodel')),
            ],
            options={
                'verbose_name': 'User STT credit',
                'verbose_name_plural': 'User STT credits',
                'db_table': 'user_stt_credit_rate',
            },
        ),
        migrations.CreateModel(
            name='UserTTSRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts', to='rate.userratemodel')),
            ],
            options={
                'verbose_name': 'User TTS credit',
                'verbose_name_plural': 'User TTS credits',
                'db_table': 'user_tts_rate',
            },
        ),
        migrations.CreateModel(
            name='UserTTSCreditRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.PositiveIntegerField(default=0)),
                ('usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('reset', models.DateTimeField(blank=True, null=True)),
                ('tts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='rate.userttsratemodel')),
            ],
            options={
                'verbose_name': 'User TTS credit',
                'verbose_name_plural': 'User TTS credits',
                'db_table': 'user_tts_credit_rate',
            },
        ),
    ]
