# Generated by Django 5.2.7 on 2026-01-23 14:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm', '0001_initial'),
        ('plan', '0001_initial'),
        ('service', '0001_initial'),
        ('sub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLLMRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_time', models.PositiveIntegerField(default=0)),
                ('session_limit', models.SmallIntegerField(default=0)),
                ('context_limit', models.SmallIntegerField(default=0)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_rate', to='plan.planmodel')),
            ],
            options={
                'verbose_name': 'Plan LLM',
                'verbose_name_plural': 'Plan LLM',
                'db_table': 'plan_llm_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanSTTRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_time', models.PositiveIntegerField(default=0)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stt_rate', to='plan.planmodel')),
            ],
            options={
                'verbose_name': 'Plan STT',
                'verbose_name_plural': 'Plan STT',
                'db_table': 'plan_stt_rate',
            },
        ),
        migrations.CreateModel(
            name='PlanTTSRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_time', models.PositiveIntegerField(default=0)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts_rate', to='plan.planmodel')),
            ],
            options={
                'verbose_name': 'Plan TTS',
                'verbose_name_plural': 'Plan TTS',
                'db_table': 'plan_tts_rate',
            },
        ),
        migrations.CreateModel(
            name='SubLLMRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_time', models.PositiveIntegerField(default=0)),
                ('session_limit', models.SmallIntegerField(default=0)),
                ('context_limit', models.SmallIntegerField(default=0)),
                ('sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_rate', to='sub.submodel')),
            ],
            options={
                'verbose_name': 'Sub LLM',
                'verbose_name_plural': 'Sub LLM',
                'db_table': 'sub_llm_rate',
            },
        ),
        migrations.CreateModel(
            name='SubSTTRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_time', models.PositiveIntegerField(default=0)),
                ('sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stt_rate', to='sub.submodel')),
            ],
            options={
                'verbose_name': 'Sub STT',
                'verbose_name_plural': 'Sub STT',
                'db_table': 'sub_stt_rate',
            },
        ),
        migrations.CreateModel(
            name='SubTTSRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_time', models.PositiveIntegerField(default=0)),
                ('sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts_rate', to='sub.submodel')),
            ],
            options={
                'verbose_name': 'Sub TTS',
                'verbose_name_plural': 'Sub TTS',
                'db_table': 'sub_tts_rate',
            },
        ),
        migrations.CreateModel(
            name='TokenLLMContextRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_limit', models.SmallIntegerField(default=0)),
                ('context_usage', models.SmallIntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_context_rate', to='llm.tokenllmsessionmodel')),
            ],
            options={
                'verbose_name': 'Token LLM context',
                'verbose_name_plural': 'Token LLM context',
                'db_table': 'token_llm_context_rate',
            },
        ),
        migrations.CreateModel(
            name='TokenLLMRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_time', models.PositiveIntegerField(default=0)),
                ('credit_usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_reset', models.DateTimeField(blank=True, null=True)),
                ('session_limit', models.SmallIntegerField(default=0)),
                ('session_usage', models.SmallIntegerField(default=0)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_rate', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token LLM',
                'verbose_name_plural': 'Token LLM',
                'db_table': 'token_llm_rate',
            },
        ),
        migrations.CreateModel(
            name='TokenSTTRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_time', models.PositiveIntegerField(default=0)),
                ('credit_usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_reset', models.DateTimeField(blank=True, null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stt_rate', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token STT',
                'verbose_name_plural': 'Token STT',
                'db_table': 'token_stt_rate',
            },
        ),
        migrations.CreateModel(
            name='TokenTTSRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_time', models.PositiveIntegerField(default=0)),
                ('credit_usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_reset', models.DateTimeField(blank=True, null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts_rate', to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token TTS',
                'verbose_name_plural': 'Token TTS',
                'db_table': 'token_tts_rate',
            },
        ),
        migrations.CreateModel(
            name='UserLLMContextRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_limit', models.SmallIntegerField(default=0)),
                ('context_usage', models.SmallIntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_context_rate', to='llm.userllmsessionmodel')),
            ],
            options={
                'verbose_name': 'User LLM context',
                'verbose_name_plural': 'User LLM context',
                'db_table': 'user_llm_context_rate',
            },
        ),
        migrations.CreateModel(
            name='UserLLMRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_time', models.PositiveIntegerField(default=0)),
                ('credit_usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_reset', models.DateTimeField(blank=True, null=True)),
                ('session_limit', models.SmallIntegerField(default=0)),
                ('session_usage', models.SmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_rate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User LLM',
                'verbose_name_plural': 'User LLM',
                'db_table': 'user_llm_rate',
            },
        ),
        migrations.CreateModel(
            name='UserSTTRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_time', models.PositiveIntegerField(default=0)),
                ('credit_usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_reset', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stt_rate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User STT',
                'verbose_name_plural': 'User STT',
                'db_table': 'user_stt_rate',
            },
        ),
        migrations.CreateModel(
            name='UserTTSRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_time', models.PositiveIntegerField(default=0)),
                ('credit_usage', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_reset', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts_rate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User TTS',
                'verbose_name_plural': 'User TTS',
                'db_table': 'user_tts_rate',
            },
        ),
    ]
