# Generated by Django 5.2.7 on 2025-11-21 12:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('chargeable', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
                'db_table': 'balance',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('uzs', 'uzs'), ('usd', 'usd')], default='uzs')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed'), ('canceled', 'canceled')], default='pending')),
                ('provider', models.CharField(choices=[('xazna', 'xazna'), ('click', 'click'), ('payme', 'payme')], default='xazna')),
                ('method', models.CharField(choices=[('uzcard', 'uzcard'), ('humo', 'humo'), ('visa', 'visa'), ('mastercard', 'mastercard'), ('unionpay', 'unionpay')], default='uzcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('operation', models.CharField(choices=[('tts', 'tts'), ('stt', 'stt'), ('llm', 'llm')])),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('cash', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('consumer', models.CharField(choices=[('service', 'service'), ('user', 'user')], default='user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expense',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('operation', 'operation_id'), name='unique_operation_and_id')],
            },
        ),
    ]
