# Generated by Django 5.2.7 on 2026-01-23 14:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('chargeable', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
                'db_table': 'balance',
            },
        ),
        migrations.CreateModel(
            name='TokenExpenseModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('operation', models.CharField(choices=[('tts', 'tts'), ('stt', 'stt'), ('llm', 'llm')])),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('cash', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('consumer', models.CharField(choices=[('service', 'service'), ('user', 'user')], default='user')),
                ('is_deleted', models.BooleanField(default=False)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicetokenmodel')),
            ],
            options={
                'verbose_name': 'Token Expense',
                'verbose_name_plural': 'Token Expenses',
                'db_table': 'token_expense',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('operation', 'operation_id'), name='unique_token_expense_operation')],
            },
        ),
        migrations.CreateModel(
            name='UserExpenseModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('operation', models.CharField(choices=[('tts', 'tts'), ('stt', 'stt'), ('llm', 'llm')])),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('cash', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('consumer', models.CharField(choices=[('service', 'service'), ('user', 'user')], default='user')),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Expense',
                'verbose_name_plural': 'User Expenses',
                'db_table': 'user_expense',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('operation', 'operation_id'), name='unique_user_expense_operation')],
            },
        ),
    ]
