# Generated by Django 5.2.7 on 2025-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenexpensemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexpensemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
