# Generated by Django 5.2.7 on 2025-11-12 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_chatsessionmodel_first_content'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessagemodel'),
        ),
    ]
