# Generated by Django 5.2.7 on 2025-11-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expensemodel_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='operation',
            field=models.CharField(choices=[('tts', 'tts'), ('stt', 'stt'), ('chat', 'chat')]),
        ),
    ]
