# Generated by Django 5.2.7 on 2025-11-13 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_expensemodel_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
