// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/auth/reset-password" | "/[locale]/auth/reset-password/confirm/[slug]" | "/[locale]/auth/sign-in" | "/[locale]/auth/sign-up" | "/[locale]/auth/verify/email/[slug]" | "/[locale]/chatbot" | "/[locale]/chatbot/[sessionId]" | "/[locale]/docs" | "/[locale]/keys" | "/[locale]/keys/[keyId]/monitoring" | "/[locale]/monitoring" | "/[locale]/stt" | "/[locale]/sub" | "/[locale]/transactions" | "/[locale]/tts" | "/[locale]/user/profile"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]" | "/media/[[...path]]" | "/protected/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/auth/reset-password": { "locale": string; }
  "/[locale]/auth/reset-password/confirm/[slug]": { "locale": string; "slug": string; }
  "/[locale]/auth/sign-in": { "locale": string; }
  "/[locale]/auth/sign-up": { "locale": string; }
  "/[locale]/auth/verify/email/[slug]": { "locale": string; "slug": string; }
  "/[locale]/chatbot": { "locale": string; }
  "/[locale]/chatbot/[sessionId]": { "locale": string; "sessionId": string; }
  "/[locale]/docs": { "locale": string; }
  "/[locale]/keys": { "locale": string; }
  "/[locale]/keys/[keyId]/monitoring": { "locale": string; "keyId": string; }
  "/[locale]/monitoring": { "locale": string; }
  "/[locale]/stt": { "locale": string; }
  "/[locale]/sub": { "locale": string; }
  "/[locale]/transactions": { "locale": string; }
  "/[locale]/tts": { "locale": string; }
  "/[locale]/user/profile": { "locale": string; }
  "/api/[[...path]]": { "path"?: string[]; }
  "/media/[[...path]]": { "path"?: string[]; }
  "/protected/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
