// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/[locale]/auth/reset-password/confirm/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/reset-password/confirm/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/auth/reset-password/confirm/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/auth/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/sign-in">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/auth/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/auth/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/sign-up">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/auth/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/auth/verify/email/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/verify/email/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/auth/verify/email/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/chatbot/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chatbot/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/chatbot/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/chatbot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chatbot">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/chatbot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/docs">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/keys/[keyId]/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/keys/[keyId]/monitoring">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/keys/[keyId]/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/keys">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/monitoring">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/stt/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/stt">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/stt/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/sub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sub">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/sub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/transactions">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/tts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tts">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/tts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/user/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/user/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/user/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
