# Generated by Django 5.2.7 on 2025-10-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmodelmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsessionmodel',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='chatsessionmodel',
            name='rate_usage',
        ),
    ]
