# Generated by Django 5.2.7 on 2025-10-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatsessionmodel_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagemodel',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
