# Generated by Django 5.2.7 on 2025-10-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessagemodel_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsessionmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AddField(
            model_name='chatsessionmodel',
            name='first_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
