# Generated by Django 5.2.7 on 2025-10-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatsessionmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessagemodel',
            name='status',
        ),
        migrations.AlterField(
            model_name='chatmessagemodel',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('system', 'system')], max_length=20),
        ),
    ]
