# Generated by Django 5.2.7 on 2025-10-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chatmessagemodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionmodel',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessagemodel',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=20),
        ),
    ]
