# Generated by Django 5.2.7 on 2025-10-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatsessionmodel_is_streaming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsessionmodel',
            name='first_content',
        ),
    ]
