# Generated by Django 5.2.7 on 2025-11-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_chatsessionmodel_first_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionmodel',
            name='context',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsessionmodel',
            name='context_expense',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
