# Generated by Django 5.2.7 on 2025-11-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatsessionmodel_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagemodel',
            name='mdl',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
