# Generated by Django 5.2.7 on 2025-11-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatmessagemodel_mdl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagemodel',
            name='mdl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
